import { 
  CreateExtensionServiceWorkerMLCEngine, 
  type ChatCompletionMessageParam,
  InitProgressReport,
  prebuiltAppConfig
} from "@mlc-ai/web-llm";
import { logger } from './logger';
import { modelState } from './modelState';

export interface ChatOptions {
  messages: ChatCompletionMessageParam[];
  config: {
    model: string;
    temperature: number;
    topP: number;
    maxTokens: number;
    stream: boolean;
  };
  onUpdate?: (message: string, chunk: string) => void;
  onFinish?: (message: string) => void;
  onError?: (error: string) => void;
}

interface LLMConfig {
  model: string;
  temperature: number;
  top_p: number;
  max_tokens: number;
  stream: boolean;
}

export class WebLLMClient {
  private engine: any = null;
  private initialized = false;
  private llmConfig?: LLMConfig;

  constructor() {
    // Initialize with default config
  }

  private async initModel(): Promise<void> {
    if (!this.llmConfig) {
      throw Error("llmConfig is undefined");
    }

    // Signal model loading start
    modelState.setLoading(true, 'Initializing model...');

    // Create engine config with Cache API (Chrome recommended for AI models)
    const engineConfig = {
      appConfig: {
        ...prebuiltAppConfig,
        useIndexedDBCache: false, // Use Cache API as recommended by Chrome
      },
      initProgressCallback: (report: InitProgressReport) => {
        // Update global model state
        modelState.setProgress(report.progress || 0, report.text);
      }
    };

    this.engine = await CreateExtensionServiceWorkerMLCEngine(
      this.llmConfig.model,
      engineConfig
    );

    this.initialized = true;
    modelState.setLoaded(true);
  }

  private isDifferentConfig(config: LLMConfig): boolean {
    if (!this.llmConfig) {
      return true;
    }

    // Only compare model - other parameters don't require reloading
    if (this.llmConfig.model !== config.model) {
      return true;
    }

    // temperature, top_p, max_tokens, and stream are inference parameters
    // that don't require model reloading
    return false;
  }

  async chat(options: ChatOptions): Promise<void> {
    // Convert config to LLMConfig format
    const config: LLMConfig = {
      model: options.config.model,
      temperature: options.config.temperature,
      top_p: options.config.topP,
      max_tokens: options.config.maxTokens,
      stream: options.config.stream
    };

    if (!this.initialized || this.isDifferentConfig(config)) {
      logger.model('Model needs initialization. Initialized:', this.initialized, 'Config different:', this.isDifferentConfig(config));
      logger.debug('Current config:', this.llmConfig);
      logger.debug('New config:', config);
      
      this.llmConfig = { ...(this.llmConfig || {}), ...config };
      
      try {
        await this.initModel();
      } catch (err: any) {
        let errorMessage = err.message || err.toString() || "";
        if (errorMessage === "[object Object]") {
          errorMessage = JSON.stringify(err);
        }
        logger.error('Error while initializing the model', errorMessage);
        modelState.setLoading(false, `Error: ${errorMessage}`);
        options?.onError?.(errorMessage);
        return;
      }
    } else {
      logger.model('Model already initialized and config unchanged, skipping initialization');
    }

    let reply: string | null = "";
    
    try {
      const completion = await this.engine.chat.completions.create({
        stream: options.config.stream,
        messages: options.messages,
        temperature: options.config.temperature,
        top_p: options.config.topP,
        max_tokens: options.config.maxTokens,
      });

      if (options.config.stream) {
        for await (const chunk of completion) {
          const delta = chunk.choices[0]?.delta.content;
          if (delta) {
            reply += delta;
            options.onUpdate?.(reply, delta);
          }
        }
      } else {
        reply = completion.choices[0].message.content;
        options.onUpdate?.(reply || "", reply || "");
      }

      if (reply) {
        options.onFinish?.(reply);
      } else {
        options.onError?.("Empty response generated by LLM");
      }
    } catch (err: any) {
      let errorMessage = err.message || err.toString() || "";
      if (errorMessage === "[object Object]") {
        errorMessage = JSON.stringify(err);
      }
      
      // Handle port disconnection errors with automatic reconnection
      if (errorMessage.includes('disconnected port') || 
          errorMessage.includes('port is null') ||
          errorMessage.includes('Attempting to use a disconnected port object')) {
        logger.model('Port disconnected, attempting to reinitialize and retry');
        try {
          await this.reset();
          await this.initModel();
          
          // Retry the chat once after reconnection
          return this.chat(options);
        } catch (retryErr: any) {
          logger.error('Failed to reconnect and retry:', retryErr);
          modelState.setLoading(false, "Connection lost");
          options.onError?.("Connection lost. Please try again.");
          return;
        }
      }
      
      logger.error('Error in chatCompletion', errorMessage);
      options.onError?.(errorMessage);
    }
  }

  async reset(): Promise<void> {
    this.initialized = false;
    this.llmConfig = undefined;
    this.engine = null;
    modelState.setLoaded(false);
  }

  isModelLoaded(): boolean {
    return this.initialized && this.engine !== null;
  }

  getModelName(): string | undefined {
    return this.llmConfig?.model;
  }
}

export const webLLMClient = new WebLLMClient();